<html>
<head>
	<title>ERROR 404</title>


        <style type="text/css">
              body{
              background-repeat: no-repeat;


              }

              #princil{
                    background-image:url("public/img/404.jpg");
                    height: 380px;
                    margin: 0 auto;
                    width: 570px;
              }

              h2{
                text-align: center;
              }

              #text{

                text-align: center;

              }


        </style>


</head>
<body>


	<div id="princil">


	</div>

       <h2>Esta web no existe.</h2>
	</div>
	<div id="text"><a href="<?php echo Conectar::ruta();?>">Salir de aqui</a></div>


</body>
</html>