<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Login acreditados">


    <!-- Le styles -->
    <link href="<?php echo Conectar::ruta();?>public/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo Conectar::ruta();?>public/css/bootstrap-responsive.min.css" rel="stylesheet">

    <link rel="stylesheet" href="<?php echo Conectar::ruta();?>public/css/typica-login.css">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le favicon -->
    <style type="text/css">

          body{
            background-image: url("public/img/bg.png");
          }

           .center{
                text-align: center;
           }
    </style>


  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo Conectar::ruta();?>">Panel de administración</a>
        </div>
      </div>
    </div>

    <!-- **************************************************************************************** -->

    <?php

            if (isset($_GET["m"])) {

                 switch ($_GET["m"]) {
                   case '1':

                    ?>
                    <div class="alert alert-error center">
                      <button class="close" data-dismiss="alert">x</button>

                      <b>Nombre de usuario y la contraseña no coinciden</b>
                    </div>

                    <?php

                  break;

                  case '2':

                  ?>

                   <div class="alert alert-error center">
                        <button class="close" data-dismiss="alert">x</button>
                        <b>El usuario no existe en nuestros registros</b>
                   </div>

                  <?php

                  break;

                   case '3':

                  ?>

                   <div class="alert alert-success center">
                        <button class="close" data-dismiss="alert">x</button>
                        <b>Session cerrada con exito</b>
                   </div>

                  <?php

                  break;


                 }//end switch


            }//end if

         ?>


    <!-- ************************************************************************************* -->

    <div class="container">

        <div id="login-wraper">
            <form class="form login-form" method="post">
                <legend><span class="blue">Inicia sesión</span></legend>

                <div class="body">
                    <label>Usuario</label>
                    <input type="text" name="userLogin" autofocus>

                    <label>Contraseña</label>
                    <input type="password" placeholder="*************" name="passUser">
                </div>

                <div class="footer">



                    <input type="hidden" name="g" value="s">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>

            </form>
        </div>

    </div>






    <script src="<?php echo Conectar::ruta();?>public/js/jquery-1.8.3.js"></script>
    <script src="<?php echo Conectar::ruta();?>public/js/bootstrap.js"></script>
    <script src="<?php echo Conectar::ruta();?>public/js/typica-login.js"></script>

  </body>
</html>
