<div class="navbar navbar-inverse navbar-static-top">

          	<div class="navbar-inner navbar-inverse">
          		<div class="container">

          			<a href="#" class="brand">
                         <h5>SISTEMA LOOKUP</h5>
          			</a>


	          			    <ul class="nav">

	          			    	<div class="span7"></div>
	          			    	<li><a href="../?accion=index" target="_blank">Previsualizar</a></li>
	          			    	<li><a href="<?php echo Conectar::ruta();?>?accion=cerrar-session">Cerrar sesión</a></li>
	          			    </ul>




          		</div>
          	</div>
          </div>