<!DOCTYPE HTML>
<html lang="es">
		<head>
			<meta charset="UTF-8">
			<title>LOOKUP</title>

   	      <link rel="stylesheet" href="<?php echo Conectar::ruta();?>public/css/bootstrap.css">
	      <link rel="stylesheet" href="<?php echo Conectar::ruta();?>public/css/style.css">
	      <link rel="stylesheet" type="text/css" href="<?php echo Conectar::ruta(); ?>public/css/demo_page.css">
          <link rel="stylesheet" type="text/css" href="<?php echo Conectar::ruta(); ?>public/css/demo_table.css">


	      <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery-1.8.3.js"></script>
	      <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/bootstrap.js"></script>

	      <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="<?php echo Conectar::ruta();?>public/js/funciones.js"></script>




		</head>

		<body>

			       <div class="container">

           <div class="row">
             <div class="span12">

              <div class="hero-unit">
                      <h2>LOOKUP</h2>
                      <!-- <a href="view/repor.php" class="btn btn-primary">Generar reporte</a> -->
                      <a href="javascript:void(0);" onclick="window.location='<?php echo Conectar::ruta();?>?accion=repor'" class="btn btn-primary">Generar reporte</a>

                </div>



           <div class="span8">
                     <?php
                    if (isset($_GET["m"])) {

                       switch ($_GET["m"]) {
                         case '1':

                          ?>
                          <div class="alert alert-error center">
                            <button class="close" data-dismiss="alert">x</button>

                            <b>Seleccione una persona para eliminar</b>
                          </div>

                         <?php

                        break;

                        case '2':

                         ?>
                          <div class="alert alert-success center">
                            <button class="close" data-dismiss="alert">x</button>

                            <b>Selección eliminada con exito</b>
                          </div>

                         <?php

                        break;



                          }
                        }



                         ?>

              </div>



          <div id="todosEmpre">

                  <table cellpadding="0" cellspacing="0" border="0" class="display table table-hover" id="tabla">
                    <thead>
                      <tr>

                        <th>ID</th>
                        <th>Foto</th>
                        <th>Nombre / Apellido</th>
                        <th>Nacionalidad</th>
                        <th>Observación</th>
                        <th>Cedula</th>
                        <th>Estado</th>
                        <th>
                        	Ver datos
                          </th>

                      </tr>
                    </thead>

                    <tbody>


                            <?php


                             for ($i=0; $i < sizeof($view); $i++) {

                              



                              ?>
                                    <tr>
                                      <td>
                                           <?php echo $view[$i]["id_persona"]; ?>
                                      </td>

                                       <td>
                                         <?php

                                             if (!empty($view[$i]["foto"])=="") {
                                              ?>

                                               <img src="<?php echo Conectar::ruta(); ?>/public/foto/perfil.png" alt="">
                                               <?php

                                             }else{
                                              ?>

                                                <img src="<?php echo Conectar::ruta(); ?>/public/foto/<?php echo $view[$i]["foto"];?>" alt="">

                                               <?php

                                             }

                                           ?>
                                      </td>

                                       <td>
                                             <?php echo $view[$i]["nombre"]; ?>
                                      </td>

                                       <td>
                                             <?php echo $view[$i]["nacionalidad"]; ?>
                                      </td>
                                       <td>

                                        <?php echo $view[$i]["observacion"]; ?>


                                      </td>

                                      <td>

                                       <small> <?php echo $view[$i]["cedula_pasaporte"]; ?></small>


                                      </td>

                                      <!-- ******************************************************** -->

                                       <td>
                                             <?php
                                                   echo $view[$i]["estado"];




                                               ?>
                                      </td>

                                     <td>
                                            <a href="<?php echo Conectar::ruta();?>?accion=view&data=<?php echo base64_encode($view[$i]["id_persona"]) ?>&en=<?php echo md5('dsfsdfdsfdsfds') ?>">

                                            <img src="<?php echo Conectar::ruta();?>public/img/view_text.png" alt="view" title="Ver datos de <?php echo $view[$i]["nombre"]; ?>">

                                             </a>


                                      </td>


                                    </tr>

                                <?php
                                  }

                                     
                            ?>





                    </tbody>

                  </table>

             </div><!-- end todosEmpre -->




             </div>

                <center>

                  <div class="san3">

                      <!-- <a href="javascript:void();" onclick="window.location='?accion=pdfTab'" class="btn btn-primary">
                        Exportar a PDF
                      </a> -->

                 </div>

                </center>


           </div>

       </div><!--  end container -->





		</body>


</html>